global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateways
    static_configs:
      - targets:
          - gateway-us:8080
          - gateway-eu:8080
          - gateway-asia:8080
